#line 2 "lex.yy.cpp"

#line 4 "lex.yy.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 39
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 50
#define YY_END_OF_BUFFER 51
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[308] =
    {   0,
       48,   48,    0,    0,   39,   39,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   51,   49,   48,    1,
        1,   49,   49,   49,   49,   50,   39,   50,   46,   47,
       45,   44,   50,   50,   50,   50,   41,   20,   50,    8,
       50,    9,   50,   12,   50,   14,   13,   50,   16,   50,
       50,   17,   50,   50,   18,   50,   50,   32,   50,   33,

       34,   50,   50,   50,   38,   37,   35,   21,   50,   22,
       23,   50,   27,   50,   50,   50,   50,   25,   24,   50,
       31,   30,   50,   29,   50,   48,    0,    0,    0,    0,
        0,   39,    0,    0,   43,   44,    0,    0,   45,    0,
       41,   20,    0,    0,    0,    0,    9,    0,   12,    0,
       12,    0,   14,    0,   13,    0,   16,    0,   16,    0,
        0,   17,    0,    0,    0,   18,    0,    0,    0,   32,
        0,   33,   33,   34,    0,    0,    0,   38,   37,   38,
       37,   35,   21,    0,   22,   22,   23,    0,   27,   27,
        0,    0,    0,    0,    0,   25,   24,   25,   24,    0,

       31,   30,   31,   30,    0,   29,   29,    0,    0,    0,
        0,    0,    0,   45,    0,   42,    0,    9,    0,   13,
        0,    0,    0,   36,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   42,    0,    9,   11,   13,    0,
       10,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   11,   15,   10,   19,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   15,   19,   28,   26,    0,
        0,    0,    0,    2,    0,    0,   28,    0,    0,    0,
        0,    0,    7,    0,    0,    0,    0,    0,    7,    0,
        0,    0,    0,   40,    0,    0,    5,    0,    0,   40,

        0,    3,    6,   40,    4,   40,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    1,    1,    1,    1,    1,    6,
        7,    8,    9,   10,    9,   11,   12,   13,   14,   15,
       14,   14,   14,   14,   14,   14,   14,    1,    1,   16,
       16,   16,    1,    1,   17,   18,   19,   20,   21,   22,
        1,   23,   24,    1,    1,   25,   26,   27,   28,   29,
        1,   30,   31,   32,   33,   34,   35,    1,   36,    1,
       37,    1,   38,    1,    1,    1,   39,   39,   39,   39,

       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[40] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[312] =
    {   0,
        0,   30,    0,    0,   61,    0,  528,  527,    3,    5,
        4,    6,  526,  525,    1,    2,  524,  523,   99,  133,
      522,  521,   13,   15,  520,  519,  109,  114,  518,  517,
       16,   37,  516,  515,    5,   14,   45,   46,  551,  550,
      512,  511,  102,  104,  510,  509,  113,  118,  119,  120,
      121,  131,  145,  155,  158,  161,  547,  568,  544,  568,
      568,  515,    0,  517,  522,  568,  130,  537,  568,  568,
      568,   44,  514,  512,  509,  517,  166,  169,  105,  568,
      513,  176,  176,  534,  505,  179,  186,  193,  532,  503,
      509,  196,  124,  501,  199,   25,  507,  209,  154,  527,

      216,  501,  495,  230,  524,  523,  522,  228,  200,  521,
      231,  214,  520,  165,  500,  503,  247,  517,  516,  249,
      515,  514,  510,  247,  481,  511,  491,  486,  482,  478,
      483,  205,  477,  501,  568,  250,  485,  472,  483,  463,
      258,  261,  232,  477,  469,  460,  266,  217,  496,  467,
      494,  467,  269,  455,  274,  276,  491,  469,  489,  470,
      468,  277,  137,  458,  459,  280,  215,  463,  464,  288,
      304,  482,  481,  307,  450,  451,  305,  478,  477,  476,
      475,  474,  310,  312,  473,  472,  315,  329,  471,  470,
      307,  450,  445,  444,  330,  466,  465,  464,  463,  332,

      462,  461,  460,  459,  455,  568,  330,  434,  441,  436,
      427,  434,  433,  568,  432,  337,  420,  342,  425,  345,
      420,  423,  418,  568,  432,  425,  412,  419,  411,  410,
      439,  410,  420,  408,  348,  413,  351,  434,  354,  414,
      432,  412,  419,  412,  409,  408,  407,  234,  395,  393,
      422,  395,  419,  417,  416,  415,  384,  384,  412,  411,
      395,  409,  408,  315,  390,  406,  405,  404,  568,  266,
      351,  387,  146,  402,  355,  357,  386,  369,  355,  358,
      355,  378,  372,  354,  343,  349,  316,  103,  345,  316,
      310,  324,  271,  364,  275,  256,  251,  245,  187,  381,

      202,  167,  127,  384,  112,  387,  568,   50,   45,   11,
        0
    } ;

static yyconst flex_int16_t yy_def[312] =
    {   0,
      308,  308,  309,  309,  307,    5,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  310,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,

      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  311,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  310,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,

      307,  307,  307,  307,  311,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,

      307,  307,  307,  307,  307,  307,    0,  307,  307,  307,
      307
    } ;

static yyconst flex_int16_t yy_nxt[608] =
    {   0,
      205,   59,   60,   61,   79,   83,   79,   83,   80,   80,
       80,  134,   80,   84,   93,   84,   93,   99,   62,   63,
      128,  100,   81,   64,   81,   85,  167,   85,  102,  129,
       65,   59,   60,   61,   94,  103,   94,  102,   99,   82,
       82,   82,  100,   82,  103,   66,  104,  104,   62,   63,
       58,  105,  105,   64,  106,  106,  136,  136,  136,  168,
       65,   66,   67,   60,   60,   68,   69,   70,   71,   71,
       66,   66,   71,   72,   72,   72,   71,   73,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   74,   75,   66,
       66,   76,   66,   66,   66,   66,   66,   69,   70,   77,

       88,   60,   60,  109,  288,  109,  143,  110,   89,  110,
       96,   60,   60,  305,  112,   96,   60,   60,  113,  112,
      114,  114,  117,  113,  144,  163,   90,  118,  303,   76,
      119,  132,  117,   91,   88,   60,   60,  118,  163,   76,
      119,  294,   89,   97,   76,  164,  120,  273,   97,  115,
      115,  121,  116,  116,  122,  171,  120,  133,  164,  172,
       90,  121,  123,   76,  122,  123,  191,   91,  302,  281,
      124,  124,  124,  124,  124,  124,  140,  148,  141,  141,
      141,  142,  142,  142,  125,  149,  146,  125,  147,  147,
      147,  153,  153,  153,  156,  192,  154,  150,  155,  155,

      155,  184,  157,  305,  141,  185,  132,  142,  162,  162,
      162,  166,  166,  166,  147,  188,  167,  153,  148,  189,
      133,  170,  170,  170,  155,  304,  149,  158,  174,  174,
      174,  177,  133,  143,  162,  248,  178,  166,  150,  179,
      183,  183,  183,  187,  187,  187,  303,  170,  195,  168,
      200,  144,  297,  196,  174,  201,  197,  302,  202,  207,
      207,  207,  136,  136,  136,  261,  183,  270,  140,  187,
      141,  141,  141,  142,  142,  142,  146,  156,  147,  147,
      147,  153,  153,  153,  154,  157,  155,  155,  155,  162,
      162,  162,  166,  166,  166,  301,  141,  278,  298,  142,

      170,  170,  170,  133,  147,  171,  177,  153,  191,  172,
      158,  178,  155,  184,  179,  162,  264,  185,  166,  174,
      174,  174,  183,  183,  183,  297,  170,  187,  187,  187,
      188,  195,  275,  200,  189,  296,  196,  192,  201,  197,
      295,  202,  207,  207,  207,  174,  289,  293,  183,  235,
      235,  235,  271,  187,  237,  237,  237,  239,  239,  239,
      235,  235,  235,  237,  237,  237,  239,  239,  239,  292,
      291,  290,  279,  289,  299,  235,  300,  300,  300,  288,
      237,  287,  286,  239,  285,  284,  235,  277,  283,  237,
      282,  299,  239,  300,  300,  300,  306,  306,  306,  306,

      306,  306,  300,  274,  280,  277,  267,  266,  276,  274,
      273,  272,  271,  270,  269,  268,  267,  255,  266,  300,
      253,  265,  306,  264,  263,  306,  262,  260,  259,  258,
      257,  224,  256,  255,  254,  253,  252,  251,  250,  249,
      248,  247,  246,  206,  245,  244,  243,  242,  241,  240,
      238,  236,  234,  233,  232,  231,  230,  229,  228,  206,
      204,  203,  204,  203,  199,  198,  199,  198,  227,  226,
      193,  190,  190,  186,  186,  182,  181,  180,  181,  180,
      225,  224,  173,  173,  223,  169,  222,  165,  221,  215,
      159,  161,  159,  220,  219,  151,  152,  151,  218,  217,

      145,  216,  215,  214,  214,  135,  160,  213,  212,  211,
      210,  209,  126,  208,  206,  204,  203,  199,  198,  194,
      193,  190,  186,  182,  181,  180,  176,  175,  173,  169,
      165,  161,  160,  159,  152,  151,  145,  131,  139,  138,
      137,  135,  131,  130,  127,  126,  307,  111,  111,  108,
      108,  107,  107,  101,  101,   98,   98,   95,   95,   92,
       92,   87,   87,   86,   86,   78,   78,   57,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,

      307,  307,  307,  307,  307,  307,  307
    } ;

static yyconst flex_int16_t yy_chk[608] =
    {   0,
      311,    1,    1,    1,    9,   11,   10,   12,   15,   16,
        9,  310,   10,   11,   23,   12,   24,   31,    1,    1,
       63,   31,    9,    1,   10,   11,   96,   12,   35,   63,
        1,    2,    2,    2,   23,   35,   24,   36,   32,   15,
       16,    9,   32,   10,   36,  309,   37,   38,    2,    2,
      308,   37,   38,    2,   37,   38,   72,   72,   72,   96,
        2,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,

       19,   19,   19,   43,  288,   44,   79,   43,   19,   44,
       27,   27,   27,  305,   47,   28,   28,   28,   47,   48,
       49,   50,   51,   48,   79,   93,   19,   51,  303,   19,
       51,   67,   52,   19,   20,   20,   20,   52,  163,   27,
       52,  288,   20,   27,   28,   93,   53,  273,   28,   49,
       50,   53,   49,   50,   53,   99,   54,   67,  163,   99,
       20,   54,   55,   20,   54,   56,  114,   20,  302,  273,
       55,   55,   55,   56,   56,   56,   77,   83,   77,   77,
       77,   78,   78,   78,   55,   83,   82,   56,   82,   82,
       82,   86,   86,   86,   88,  114,   87,   83,   87,   87,

       87,  109,   88,  301,   77,  109,  132,   78,   92,   92,
       92,   95,   95,   95,   82,  112,  167,   86,  148,  112,
       88,   98,   98,   98,   87,  299,  148,   88,  101,  101,
      101,  104,  132,  143,   92,  248,  104,   95,  148,  104,
      108,  108,  108,  111,  111,  111,  298,   98,  117,  167,
      120,  143,  297,  117,  101,  120,  117,  296,  120,  124,
      124,  124,  136,  136,  136,  248,  108,  270,  141,  111,
      141,  141,  141,  142,  142,  142,  147,  156,  147,  147,
      147,  153,  153,  153,  155,  156,  155,  155,  155,  162,
      162,  162,  166,  166,  166,  295,  141,  270,  293,  142,

      170,  170,  170,  156,  147,  171,  177,  153,  191,  171,
      156,  177,  155,  184,  177,  162,  264,  184,  166,  174,
      174,  174,  183,  183,  183,  292,  170,  187,  187,  187,
      188,  195,  264,  200,  188,  291,  195,  191,  200,  195,
      290,  200,  207,  207,  207,  174,  289,  287,  183,  216,
      216,  216,  271,  187,  218,  218,  218,  220,  220,  220,
      235,  235,  235,  237,  237,  237,  239,  239,  239,  286,
      285,  284,  271,  283,  294,  216,  294,  294,  294,  282,
      218,  281,  280,  220,  279,  278,  235,  277,  276,  237,
      275,  300,  239,  300,  300,  300,  304,  304,  304,  306,

      306,  306,  294,  274,  272,  268,  267,  266,  265,  263,
      262,  261,  260,  259,  258,  257,  256,  255,  254,  300,
      253,  252,  304,  251,  250,  306,  249,  247,  246,  245,
      244,  243,  242,  241,  240,  238,  236,  234,  233,  232,
      231,  230,  229,  228,  227,  226,  225,  223,  222,  221,
      219,  217,  215,  213,  212,  211,  210,  209,  208,  205,
      204,  203,  202,  201,  199,  198,  197,  196,  194,  193,
      192,  190,  189,  186,  185,  182,  181,  180,  179,  178,
      176,  175,  173,  172,  169,  168,  165,  164,  161,  160,
      159,  158,  157,  154,  152,  151,  150,  149,  146,  145,

      144,  140,  139,  138,  137,  134,  133,  131,  130,  129,
      128,  127,  126,  125,  123,  122,  121,  119,  118,  116,
      115,  113,  110,  107,  106,  105,  103,  102,  100,   97,
       94,   91,   90,   89,   85,   84,   81,   76,   75,   74,
       73,   68,   65,   64,   62,   59,   57,   46,   45,   42,
       41,   40,   39,   34,   33,   30,   29,   26,   25,   22,
       21,   18,   17,   14,   13,    8,    7,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,

      307,  307,  307,  307,  307,  307,  307
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scan.l"
#line 2 "scan.l"
#include "common.h"
#include "physicalOP.h"
#include "Field.h"
physicalOP *p = NULL;
Qtree *current_qt =NULL;
Qtree *head = NULL;
stack<Qexpression*> output_s;
stack<Qexpression*> operators_s;
int precedence(string);
int noperands(string) ;

vector<string> field_names ;
vector<enum FIELD_TYPE > field_types ;
string table_name ;
vector<int> int_values;
vector<string> str_values ;
vector<string> temp_relations ;

std::ostream error_output(NULL);

int start_time, stop_time;





























#line 747 "lex.yy.cpp"

#define INITIAL 0
#define DISTINCT_STATE 1
#define WHERE_SUB_STATEMENT 2
#define DROP_TABLE_STATEMENT 3
#define SELECT_STATEMENT 4
#define S_S_EXPECT_FROM_OR_COMMA 5
#define S_S_EXPECT_TABLES 6
#define S_S_DISTINCT_STATE 7
#define S_S_EXPECT_COLUMNS 8
#define S_S_EXPECT_WHERE_OR_COMMA 9
#define S_S_EXPECT_MORE_TABLES 10
#define S_S_EXPECT_FROM 11
#define DELETE_STATEMENT 12
#define D_S_EXPECT_WHERE 13
#define CREATE_TABLE_STATEMENT 14
#define C_T_S_EXPECT_LEFT_PARENTHESIS 15
#define C_T_S_EXPECT_ATTR 16
#define C_T_S_EXPECT_TYPE 17
#define C_T_S_EXPECT_COMMA_OR_RIGHT_PARENTHESIS 18
#define C_T_S_EXPECT_WS 19
#define INSERT_STATEMENT 20
#define I_S_EXPECT_LEFT_PARENTHESIS 21
#define I_S_EXPECT_ATTR 22
#define I_S_VALUES_EXPECT_LEFT_PARENTHESIS 23
#define I_S_EXPECT_VALUES_OR_SELECT 24
#define I_S_EXPECT_COMMA_OR_RIGHT_PARENTHESIS 25
#define I_S_VALUES_EXPECT_COMMA_OR_RIGHT_PARENTHESIS 26
#define I_S_VALUES_EXPECT_value 27

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

        static int yy_start_stack_ptr = 0;
        static int yy_start_stack_depth = 0;
        static int *yy_start_stack = NULL;
    
    static void yy_push_state (int new_state );
    
    static void yy_pop_state (void );
    
    static int yy_top_state (void );
    
/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 105 "scan.l"


#line 1001 "lex.yy.cpp"

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 308 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 568 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(D_S_EXPECT_WHERE):
case YY_STATE_EOF(S_S_EXPECT_WHERE_OR_COMMA):
case YY_STATE_EOF(WHERE_SUB_STATEMENT):
#line 107 "scan.l"
{

	cout << endl << "";
	if(YY_START == WHERE_SUB_STATEMENT){
		while(operators_s.empty() != true){
			if (noperands(operators_s.top()->str) == 2) {
				operators_s.top()->right =  (output_s.top() )  ; output_s.pop() ;
				operators_s.top()->left =  (output_s.top() )  ; output_s.pop() ;
				operators_s.top()->tables.insert(
					operators_s.top()->left->tables.begin() , operators_s.top()->left->tables.end() ) ;
				operators_s.top()->tables.insert(
					operators_s.top()->right->tables.begin() , operators_s.top()->right->tables.end() ) ;
			}else if (noperands(operators_s.top()->str) == 1) {
				operators_s.top()->left =  (output_s.top() )  ; output_s.pop() ;
				operators_s.top()->tables.insert(
					operators_s.top()->left->tables.begin() , operators_s.top()->left->tables.end() ) ;
			}
			output_s.push(operators_s.top()); operators_s.pop() ;
		}
		#ifdef DEBUG
		output_s.top()->print(0) ; 
		#endif
	}
	if(head != NULL){
		head->exec(true, NULL);
		head->free();
		head = (current_qt = NULL);
	}
	if(YY_START == WHERE_SUB_STATEMENT){
		yy_pop_state();
		if(YY_START == D_S_EXPECT_WHERE){
			p->Delete(table_name, output_s.empty()? NULL: output_s.top() ) ;
		}
		while(! output_s.empty() ){ output_s.top()->free() ;output_s.pop();}
	}else if(YY_START == D_S_EXPECT_WHERE){
		p->Delete(table_name, NULL) ;
	}

	cout << "Disk IOs: " << p->IO() << endl ; 
	stop_time = clock() ;
	cout << "Execution Time: " << ( stop_time - start_time ) / double(CLOCKS_PER_SEC) << " s" << endl ;
	cout << endl << "=================================" << endl << endl;
	yyterminate();
}
	YY_BREAK
case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 151 "scan.l"
{
	cout << endl << "";
	if(YY_START == WHERE_SUB_STATEMENT){
		while(operators_s.empty() != true){
			if (noperands(operators_s.top()->str) == 2) {
				operators_s.top()->right =  (output_s.top() )  ; output_s.pop() ;
				operators_s.top()->left =  (output_s.top() )  ; output_s.pop() ;
				operators_s.top()->tables.insert(
					operators_s.top()->left->tables.begin() , operators_s.top()->left->tables.end() ) ;
				operators_s.top()->tables.insert(
					operators_s.top()->right->tables.begin() , operators_s.top()->right->tables.end() ) ;
			}else if (noperands(operators_s.top()->str) == 1) {
				operators_s.top()->left =  (output_s.top() )  ; output_s.pop() ;
				operators_s.top()->tables.insert(
					operators_s.top()->left->tables.begin() , operators_s.top()->left->tables.end() ) ;
			}
			output_s.push(operators_s.top()); operators_s.pop() ;
		}
		#ifdef DEBUG
		output_s.top()->print(0) ;
		#endif
	}
	if(head != NULL){
		head->exec(true, NULL);
		head->free();
		head = (current_qt = NULL);
	}
	if(YY_START == WHERE_SUB_STATEMENT){
		yy_pop_state();
		if(YY_START == D_S_EXPECT_WHERE){
			p->Delete(table_name, output_s.empty()? NULL: output_s.top() ) ;
		}
		while(! output_s.empty() ){ output_s.top()->free() ;output_s.pop();}
	}else if(YY_START == D_S_EXPECT_WHERE){
		p->Delete(table_name, NULL) ;
	}
	for(vector<string>::iterator it = temp_relations.begin(); it != temp_relations.end(); ){
		p->DropTable(*it) ;it = temp_relations.erase(it) ;
	}
	BEGIN(INITIAL);
	
	cout << "Disk IOs: " << p->IO() << endl ; 
	stop_time = clock() ;
	cout << "Execution Time: " << ( stop_time - start_time ) / double(CLOCKS_PER_SEC) << " s" <<endl ;
	cout << endl << "=================================" << endl << endl;
	p->IOreset() ;
	start_time = clock();
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 200 "scan.l"
{
	cout <<"" << "SELECT " ;
	err_out_START("SELECT");
	yy_push_state(SELECT_STATEMENT);
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 205 "scan.l"
{
	cout <<""<< "DELETE FROM " ;
	err_out_START("DELETE FROM");
	BEGIN(DELETE_STATEMENT);
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 210 "scan.l"
{
	cout <<""<< "CREATE TABLE " ;
	err_out_START("CREATE TABLE" );
	BEGIN(CREATE_TABLE_STATEMENT);
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 215 "scan.l"
{
	cout <<""<< "DROP TABLE " ;
	err_out_START("DROP TABLE" );
	BEGIN(DROP_TABLE_STATEMENT);
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 220 "scan.l"
{
	cout <<""<< "INSERT INTO ";
	err_out_START("INSERT INTO");
	BEGIN(INSERT_STATEMENT);
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 226 "scan.l"
{
	cout << "DISTINCT " ;
	head = (current_qt = new Qtree(DELTA, NULL) );
	error_output << "DISTINCT" << endl ;
	yy_pop_state();
	if(YY_START == I_S_EXPECT_VALUES_OR_SELECT){
		Qtree *ins_node = new Qtree(INS, NULL);
		ins_node->left = head ;
		head->parent = ins_node ;
		head = ins_node ;
		ins_node->info.push_back(string(table_name) ) ;
		for(vector<string>::iterator it = field_names.begin(); it != field_names.end(); it++){
			ins_node->info.push_back(string(*it)) ;
		}
	}
	yy_push_state(S_S_DISTINCT_STATE) ;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 243 "scan.l"
{
	cout << "* " ;
	error_output << "column_name:\t" << yytext << endl ;
	yy_pop_state();
	if(YY_START == I_S_EXPECT_VALUES_OR_SELECT){
		Qtree *ins_node = new Qtree(INS, NULL);
		head = current_qt = ins_node ;
		ins_node->info.push_back(string(table_name) ) ;
		for(vector<string>::iterator it = field_names.begin(); it != field_names.end(); it++){
			ins_node->info.push_back(string(*it)) ;
		}
	}
	BEGIN(S_S_EXPECT_FROM);
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 257 "scan.l"
{ 
	cout << yytext << " " ;
	if(current_qt == NULL){head = ( current_qt = new Qtree(PI, NULL) );}
	else{ 
		current_qt->left = new Qtree(PI, current_qt) ;	 
		current_qt = current_qt->left;
	}
	current_qt->info.push_back(string( yytext) ) ;
	error_output << "column_name:\t" << yytext << endl ;
	yy_pop_state();
	if(YY_START == I_S_EXPECT_VALUES_OR_SELECT){
		Qtree *ins_node = new Qtree(INS, NULL);
		ins_node->left = head ;
		head->parent = ins_node ;
		head = ins_node ;
		ins_node->info.push_back(string(table_name) ) ;
		for(vector<string>::iterator it = field_names.begin(); it != field_names.end(); it++){
			ins_node->info.push_back(string(*it)) ;
		}
	}
	BEGIN(S_S_EXPECT_FROM_OR_COMMA);
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 279 "scan.l"
{
	cout << "FROM " ;
	BEGIN(S_S_EXPECT_TABLES);
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 283 "scan.l"
{
	cout << "FROM " ;
	BEGIN(S_S_EXPECT_TABLES);
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 287 "scan.l"
{
	cout << ", " ;
	BEGIN(S_S_EXPECT_COLUMNS);
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 291 "scan.l"
{
	cout << yytext << " " ;
	current_qt->info.push_back(string( yytext) );
	error_output << "column_name:\t" << yytext << endl ;
	BEGIN(S_S_EXPECT_FROM_OR_COMMA);
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 297 "scan.l"
{
	cout << yytext << " " ;
	Qtree *table_node = new Qtree(TABLE, current_qt);
	if(current_qt != NULL){ 
		current_qt->left = table_node; 
		current_qt = current_qt->left ;
	}else{ 
		current_qt = table_node; 
		head = table_node; 
	}
	current_qt->info.push_back(string( yytext) ) ;
	error_output << "table name:\t" << yytext << endl;
	BEGIN(S_S_EXPECT_WHERE_OR_COMMA);
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 311 "scan.l"
{
	cout << "WHERE" << " " ;
	yy_push_state(WHERE_SUB_STATEMENT) ;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 315 "scan.l"
{
	cout << "," << " " ;
	BEGIN(S_S_EXPECT_MORE_TABLES);
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 319 "scan.l"
{
	cout << yytext << " " ;
	Qtree *join_node = new Qtree(PRODUCT, current_qt->parent);
	Qtree *table_node = new Qtree(TABLE, join_node);
	table_node->info.push_back(string(yytext) ) ;
	join_node->info.insert(join_node->info.end(), current_qt->info.begin(), current_qt->info.end()) ;
	join_node->info.push_back(string(yytext) ) ;
	if(current_qt->parent != NULL){current_qt->parent->left = join_node ;}
	join_node->left = current_qt ;
	current_qt->parent = join_node;
	join_node->right = table_node ;
	if(head == current_qt){ 
		head = join_node;
		current_qt = join_node ; 
	}else{
		current_qt = join_node ; 
	}

	error_output << "table name: \t" << yytext << endl;
	BEGIN(S_S_EXPECT_WHERE_OR_COMMA);
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 341 "scan.l"
{/* DELETE from table */
	cout << yytext << " " ;
	error_output << "delete table:\t" << yytext << endl ;
	table_name = string(yytext) ;
	BEGIN(D_S_EXPECT_WHERE);
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 347 "scan.l"
{
	cout << "WHERE" << " " ;
	yy_push_state(WHERE_SUB_STATEMENT) ;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 354 "scan.l"
{
	cout << yytext << " " ;
	error_output << "table to Drop:\t" << yytext << endl ;
	scan_over(DROP_TABLE_STATEMENT);
	p->DropTable(yytext) ;
	BEGIN(INITIAL);
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 363 "scan.l"
{
	cout << yytext << " " ;
	error_output << "table to ins:\t" << yytext << endl;
	table_name = string(yytext) ;
	BEGIN(I_S_EXPECT_LEFT_PARENTHESIS);
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 369 "scan.l"
{
	cout << "(" << " " ;
	BEGIN(I_S_EXPECT_ATTR);
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 373 "scan.l"
{
	cout << yytext << " " ;
	error_output << "attribute :\t" << yytext <<endl ;
	field_names.push_back(string(yytext)) ;
	BEGIN(I_S_EXPECT_COMMA_OR_RIGHT_PARENTHESIS) ;
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 379 "scan.l"
{
	cout << "," << " " ;
	BEGIN (I_S_EXPECT_ATTR) ;
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 383 "scan.l"
{
	cout << ")" << " " ;
	BEGIN(I_S_EXPECT_VALUES_OR_SELECT) ;
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 387 "scan.l"
{
	cout << "VALUES" << " " ;
	BEGIN(I_S_VALUES_EXPECT_LEFT_PARENTHESIS);
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 391 "scan.l"
{
	cout << "(" << " " ;
	BEGIN(I_S_VALUES_EXPECT_value);
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 395 "scan.l"
{
	cout << "SELECT" << " " ;
	yy_push_state(SELECT_STATEMENT);
}
	YY_BREAK
case 29:
/* rule 29 can match eol */
YY_RULE_SETUP
#line 399 "scan.l"
{
	cout << yytext << " " ;
	error_output << "value:      \t" << yytext << endl;
	
	if(yytext[0] == 'N' && yytext[1] == 'U' && yytext[2] == 'L' ){
		perror("NULL is undefined");
		int_values.push_back(0) ;
	}else if(yytext[0] == '"' ) {
		string value_str(yytext + 1) ;
		str_values.push_back( value_str.substr(0, value_str.size() - 1) ) ;
	}else if(yytext[0] >= '0' && yytext[0] <= '9' ) { //No negative numbers 
		int_values.push_back(atoi(yytext) )  ;
	}else{
		perror("unknown value");
	}
	BEGIN(I_S_VALUES_EXPECT_COMMA_OR_RIGHT_PARENTHESIS);
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 416 "scan.l"
{
	cout << "," << " " ;
	BEGIN(I_S_VALUES_EXPECT_value) ;
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 420 "scan.l"
{
	cout << ")" << " " ;
	scan_over(INSERT_STATEMENT);
	for(vector<string>::iterator it = field_names.begin(); it != field_names.end(); it++ ){
		(*it) = string( table_name + "."+ (*it) )  ;
	}
	p->insert(table_name, field_names, str_values, int_values) ;
	field_names.clear();
	str_values.clear();
	int_values.clear() ;
	#ifdef DEBUG
	p->displayRelation(table_name);
	#endif
	BEGIN(INITIAL);
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 437 "scan.l"
{
	cout << yytext << " " ;
	/* Enter CREATE TABLE statement */
	error_output << "create table:\t" << yytext << endl;
	table_name = string(yytext) ;
	BEGIN(C_T_S_EXPECT_LEFT_PARENTHESIS);
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 444 "scan.l"
{
	cout << "(" << " " ;
	BEGIN(C_T_S_EXPECT_ATTR);
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 448 "scan.l"
{
	cout << yytext << " " ;
	error_output << "attribute :\t" << yytext <<endl ;
	field_names.push_back( string(yytext) ); 
	BEGIN(C_T_S_EXPECT_WS) ;
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 454 "scan.l"
{
	BEGIN(C_T_S_EXPECT_TYPE) ;
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 457 "scan.l"
{
	cout << yytext << " " ;
	error_output << "the type is:\t" << yytext << endl ;
	if(yytext[0] == 'I' && yytext[1] == 'N' && yytext[2] == 'T'){
		field_types.push_back( INT);
	}else if(yytext[0 ] == 'S' && yytext[2] == 'R' && yytext[3] == '2' ){
		field_types.push_back( STR20);
	}
	BEGIN(C_T_S_EXPECT_COMMA_OR_RIGHT_PARENTHESIS) ;
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 467 "scan.l"
{
	cout << "," << " " ;
	BEGIN(C_T_S_EXPECT_ATTR);
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 471 "scan.l"
{
	cout << ")" << " " ;
	scan_over(CREATE_TABLE_STATEMENT);
	if(field_types.size() != field_names.size() ) {
		perror("Size mismatch");
	}else{
		for(vector<string>::iterator it = field_names.begin(); it != field_names.end(); it++ ){
			(*it) = string( table_name + "."+ (*it) )  ;
		}
		p->CreateTable(table_name, field_names, field_types) ; 
		field_names.clear();
		field_types.clear();
		#ifdef DEBUG
		p->displayRelation(table_name);
		#endif
	}
	BEGIN(INITIAL);
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 491 "scan.l"
{ /* Eat white spaces */ }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 492 "scan.l"
{
	cout << "ORDER BY" << " " ;
	/* 
	ORDER BY 
	*/
	string match (yytext) , name_, name ;
	int pos  ;
	Qtree *order_node = new Qtree(TAU, current_qt->parent );
	order_node->left = current_qt;
	order_node->right = NULL;
	if(current_qt->parent != NULL){
		current_qt->parent->left = order_node ;
	}else{
		head = order_node ;
	}
	current_qt->parent = order_node ;

	pos = match.find(" BY") ;
	name_ = match.substr(pos + 3) ;
	pos = name_.rfind(' ') ;
	name = name_.substr(pos + 1) ;
	order_node->info.push_back( name ) ;
	cout << name << " " ;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 516 "scan.l"
{ 
	cout << yytext << " " ;
	output_s.push(new Qexpression(COLUMN, yytext) ) ;
	if(current_qt != NULL && current_qt->info.size() == 1){
		output_s.top()->tables.insert( current_qt->info[0]  ) ;
	}else{
		output_s.top()->tables.insert( table_name );
	}
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 525 "scan.l"
{
	string s(yytext) ;
	int found ;
	cout << yytext << " " ;
	output_s.push(new Qexpression(COLUMN, yytext) ) ;
	found = s.find('.') ;
	s = string( s.substr(0, found) );
	output_s.top()->tables.insert( s ) ;
}
	YY_BREAK
case 43:
/* rule 43 can match eol */
YY_RULE_SETUP
#line 534 "scan.l"
{ 
	cout << yytext << " " ;
	string l(yytext + 1) ;
	l = l.substr(0, l.size() - 1) ;
	output_s.push(new Qexpression(LITERAL, l) ) ;
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 540 "scan.l"
{
	cout << yytext << " " ;
	output_s.push(new Qexpression(INTEGER, atoi(yytext) ) ) ;
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 544 "scan.l"
{
	cout << yytext << " " ;
	int current_precedence = precedence(yytext);
	while( (! operators_s.empty() ) && 
		operators_s.top()->type != LEFT && 
		operators_s.top()->number >= current_precedence) {
		if (noperands(operators_s.top()->str) == 2) {
			operators_s.top()->right = (output_s.top() )  ; output_s.pop() ;
			operators_s.top()->left =  (output_s.top() )  ; output_s.pop() ;
			operators_s.top()->tables.insert(
				operators_s.top()->left->tables.begin() , operators_s.top()->left->tables.end() ) ;
			operators_s.top()->tables.insert(
				operators_s.top()->right->tables.begin() , operators_s.top()->right->tables.end() ) ;
		}else if (noperands(operators_s.top()->str) == 1) {
			operators_s.top()->left =  (output_s.top() )  ; output_s.pop() ;
			operators_s.top()->tables.insert(
				operators_s.top()->left->tables.begin() , operators_s.top()->left->tables.end() ) ;
		}
		output_s.push( operators_s.top() ) ;operators_s.pop();
	}
	operators_s.push( new Qexpression(OPERATER, current_precedence, yytext) );
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 566 "scan.l"
{
	cout << yytext << " " ;
	operators_s.push(new Qexpression(LEFT, yytext)) ;
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 570 "scan.l"
{
	cout << yytext << " " ;
	while(operators_s.top()->type != LEFT){
		if (noperands(operators_s.top()->str) == 2) {
			operators_s.top()->right =  (output_s.top() )  ; output_s.pop() ;
			operators_s.top()->left =   (output_s.top() )  ; output_s.pop() ;
			operators_s.top()->tables.insert(
				operators_s.top()->left->tables.begin() , operators_s.top()->left->tables.end() ) ;
			operators_s.top()->tables.insert(
				operators_s.top()->right->tables.begin() , operators_s.top()->right->tables.end() ) ;
		}else if (noperands(operators_s.top()->str) == 1) {
			operators_s.top()->left =   (output_s.top() )  ; output_s.pop() ;
			operators_s.top()->tables.insert(
				operators_s.top()->left->tables.begin() , operators_s.top()->left->tables.end() ) ;
		}
		output_s.push( operators_s.top() ) ;operators_s.pop();
	}
	operators_s.pop() ;
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 591 "scan.l"
{/* IGNORE white spaces */}       
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 592 "scan.l"
{/* all other character */
	fprintf(stderr, "Error: unaccepted character: %s\n", yytext) ;
	exit(EXIT_FAILURE); 
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 597 "scan.l"
ECHO;
	YY_BREAK
#line 1743 "lex.yy.cpp"
case YY_STATE_EOF(DISTINCT_STATE):
case YY_STATE_EOF(DROP_TABLE_STATEMENT):
case YY_STATE_EOF(SELECT_STATEMENT):
case YY_STATE_EOF(S_S_EXPECT_FROM_OR_COMMA):
case YY_STATE_EOF(S_S_EXPECT_TABLES):
case YY_STATE_EOF(S_S_DISTINCT_STATE):
case YY_STATE_EOF(S_S_EXPECT_COLUMNS):
case YY_STATE_EOF(S_S_EXPECT_MORE_TABLES):
case YY_STATE_EOF(S_S_EXPECT_FROM):
case YY_STATE_EOF(DELETE_STATEMENT):
case YY_STATE_EOF(CREATE_TABLE_STATEMENT):
case YY_STATE_EOF(C_T_S_EXPECT_LEFT_PARENTHESIS):
case YY_STATE_EOF(C_T_S_EXPECT_ATTR):
case YY_STATE_EOF(C_T_S_EXPECT_TYPE):
case YY_STATE_EOF(C_T_S_EXPECT_COMMA_OR_RIGHT_PARENTHESIS):
case YY_STATE_EOF(C_T_S_EXPECT_WS):
case YY_STATE_EOF(INSERT_STATEMENT):
case YY_STATE_EOF(I_S_EXPECT_LEFT_PARENTHESIS):
case YY_STATE_EOF(I_S_EXPECT_ATTR):
case YY_STATE_EOF(I_S_VALUES_EXPECT_LEFT_PARENTHESIS):
case YY_STATE_EOF(I_S_EXPECT_VALUES_OR_SELECT):
case YY_STATE_EOF(I_S_EXPECT_COMMA_OR_RIGHT_PARENTHESIS):
case YY_STATE_EOF(I_S_VALUES_EXPECT_COMMA_OR_RIGHT_PARENTHESIS):
case YY_STATE_EOF(I_S_VALUES_EXPECT_value):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 308 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 308 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 307);

		return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

    static void yy_push_state (int  new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) yyalloc(new_size  );

		else
			(yy_start_stack) = (int *) yyrealloc((void *) (yy_start_stack),new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(new_state);
}

    static void yy_pop_state  (void)
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

    static int yy_top_state  (void)
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_start_stack_ptr) = 0;
    (yy_start_stack_depth) = 0;
    (yy_start_stack) =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Destroy the start condition stack. */
        yyfree((yy_start_stack)  );
        (yy_start_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 596 "scan.l"



